# Generated by Django 5.1.7 on 2025-04-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='message',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Сообщение'),
        ),
    ]
