# Generated by Django 5.1.7 on 2025-04-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_request_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=18, verbose_name='Номер телефона')),
                ('whatsapp', models.URLField(max_length=100, verbose_name='Ссылка на WhatsApp')),
                ('telegram', models.URLField(max_length=100, verbose_name='Ссылка на Telegram')),
                ('email', models.EmailField(max_length=80, verbose_name='Email')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
    ]
