# Generated by Django 5.1.7 on 2025-04-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='vk',
            field=models.URLField(default='', max_length=100, verbose_name='Ссылка на ВК'),
            preserve_default=False,
        ),
    ]
