# Generated by Django 5.1.7 on 2025-04-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_worker_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=40, verbose_name='Заголовок')),
                ('heading_label', models.CharField(max_length=40, verbose_name='Подпись у заголовка')),
                ('lower_label', models.CharField(max_length=55, verbose_name='Надпись снизу')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
    ]
