# Generated by Django 5.1.7 on 2025-04-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_companystat'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='behance',
            field=models.URLField(default='', max_length=100, verbose_name='Ссылка на Behance'),
            preserve_default=False,
        ),
    ]
