# Generated by Django 5.1.7 on 2025-04-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_companyinfo_behance'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='github',
            field=models.URLField(default='', max_length=100, verbose_name='Ссылка на Github'),
            preserve_default=False,
        ),
    ]
