# Generated by Django 5.1.7 on 2025-05-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_companyinfo_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='behance',
        ),
    ]
