# Generated by Django 5.1.7 on 2025-05-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_remove_companyinfo_behance'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='privacy_policy',
            field=models.FileField(blank=True, null=True, upload_to='privacy-policy/', verbose_name='Политика конфиденциальности'),
        ),
    ]
