# Generated by Django 5.1.7 on 2025-05-07 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_casecategory_options'),
        ('home', '0011_remove_case_result_case_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Название')),
                ('label', models.TextField(blank=True, verbose_name='Подпись')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='home.case')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрики',
            },
        ),
    ]
