# Generated by Django 5.1.7 on 2025-05-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_casemetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemetric',
            name='label',
            field=models.CharField(max_length=50, verbose_name='Подпись'),
        ),
    ]
