# Generated by Django 5.1.7 on 2025-04-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='description',
            field=models.TextField(default='', max_length=500, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
