# Generated by Django 5.1.7 on 2025-04-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_technology_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='Выделена'),
        ),
    ]
