# Generated by Django 5.1.7 on 2025-04-25 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_casecategory_options'),
        ('home', '0009_rename_result_photo_case_result_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.casecategory', verbose_name='Категория'),
        ),
    ]
