# Generated by Django 5.1.7 on 2025-05-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_case_result_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='logo',
            field=models.FileField(upload_to='cases/logos/', verbose_name='Логотип'),
        ),
    ]
