# Generated by Django 5.1.7 on 2025-05-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_case_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='white_logo',
            field=models.FileField(blank=True, null=True, upload_to='cases/logos/', verbose_name='Белый логотип'),
        ),
        migrations.AlterField(
            model_name='case',
            name='photo',
            field=models.ImageField(upload_to='cases/backgrounds/', verbose_name='Фон карточки'),
        ),
    ]
