# Generated by Django 5.1.7 on 2025-04-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=20, verbose_name='Telegram ID')),
            ],
            options={
                'verbose_name': 'Telegram-чат',
                'verbose_name_plural': 'Telegram-чаты',
            },
        ),
    ]
